In [3]:
import numpy as np

In [4]:
np.__version__

'2.3.3'

In [11]:
arr1 = np.array([2,4,6,8,10])
print(type(arr1))

<class 'numpy.ndarray'>


In [12]:
id(arr1)

125894822569488

In [14]:
arr2 = np.copy(arr1)
arr2

array([ 2,  4,  6,  8, 10])

In [15]:
arr3 = np.array((1, 3, 5, 7, 9))
arr4 = np.array({'one':1, 'two':2})
arr5 = np.array({1,2,3,2,2,1,21})
print(arr3)
print(arr4)
print(arr5)

[1 3 5 7 9]
{'one': 1, 'two': 2}
{1, 2, 3, 21}


In [20]:
arr6 = [i for i in range(10)]
arr7 = [i for i in np.arange(1, 10, 2)]
arr8 = np.arange(10)
print(arr6, "\n", arr7)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
 [np.int64(1), np.int64(3), np.int64(5), np.int64(7), np.int64(9)]


In [21]:
len8 = len(arr8)
print(arr8.size)

10


In [22]:
np.array([111, 2.3, True])

array([111. ,   2.3,   1. ])

In [23]:
np.linspace(1, 10, 5)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
li1 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(li1).ndim

2

In [29]:
np.array([[[1,2], [3, 4]], [[5,6], [7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((2, 3), dtype='int64').astype('float32')

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [36]:
#Property of numpy array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#Size
print(a.size)
#Shape
print(a.shape)
#ndim
print(a.ndim)


9
(3, 3)
2


In [38]:
#reshape an array
a2 = np.arange(15)
print(a2)
a2.reshape((3, 5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
#Change directly the shape of array
a2.shape = (3, 5)
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
#Create an random data
data = np.random.randn(2, 3)
data

array([[ 0.85361097, -1.39489705,  0.9898034 ],
       [-1.35016459,  0.15383554,  0.12931301]])

In [44]:
np.mean(data)

np.float64(-0.10308311834814565)

In [45]:
data2 = np.random.rand(100, 100)
data2

array([[0.59779813, 0.52833016, 0.7686413 , ..., 0.0632753 , 0.14391646,
        0.92164606],
       [0.95800988, 0.8359908 , 0.76654147, ..., 0.15882692, 0.93821506,
        0.81193364],
       [0.50513773, 0.11372154, 0.30683644, ..., 0.897336  , 0.61914485,
        0.82782435],
       ...,
       [0.22868182, 0.55214138, 0.19094695, ..., 0.3972873 , 0.19498115,
        0.17494345],
       [0.13232721, 0.20074495, 0.86991706, ..., 0.72237981, 0.39178902,
        0.95541102],
       [0.72804241, 0.81226059, 0.41343748, ..., 0.44011892, 0.24839129,
        0.63377606]], shape=(100, 100))

In [46]:
np.mean(data2)

np.float64(0.4994513939909022)

In [52]:
data3 = np.random.rand(1000, 1000)
data3

array([[0.68871599, 0.53077552, 0.42388418, ..., 0.82468603, 0.23883907,
        0.78190676],
       [0.30760846, 0.66010226, 0.71012724, ..., 0.37994497, 0.80573306,
        0.89526769],
       [0.40906971, 0.89456657, 0.4539021 , ..., 0.58073691, 0.93201177,
        0.99960943],
       ...,
       [0.42509099, 0.42554309, 0.8845082 , ..., 0.85462312, 0.25474139,
        0.8700189 ],
       [0.44694058, 0.27239489, 0.41375556, ..., 0.89660071, 0.31115295,
        0.91656324],
       [0.44093458, 0.31627282, 0.72895612, ..., 0.22625967, 0.22382875,
        0.44210856]], shape=(1000, 1000))

In [51]:
np.mean(data3)

np.float64(0.49991134911763935)

In [53]:
#Add an element
a = np.array([1, 2, 3])
b = np.append(a, [4, 5,6])
b

array([1, 2, 3, 4, 5, 6])

In [57]:
a = np.array([[1, 2], [3, 4]])
b = np.append(a, [[101, 3232], [32, 32]], axis = 0)
b

array([[   1,    2],
       [   3,    4],
       [ 101, 3232],
       [  32,   32]])

# Remove an element

In [58]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.delete(a, 0)

array([2, 3, 4, 5, 6])

In [60]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.delete(a, 0, axis = 0)

array([[4, 5, 6]])

In [62]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
np.delete(a, 1, axis = 1)

array([[1, 3],
       [4, 6]])

# Operator


In [64]:
#Plus
#List
a = [1, 2, 3]
b = [4, 5, 6]
a+b

[1, 2, 3, 4, 5, 6]

In [68]:
#Numpy
a = np.array([1, 2, 3])
b = np.array([4, 5, 0])
a+b

array([5, 7, 3])

In [69]:
#If the size of vector is the same, we can plus, minus, multiply, devide
print(a-b)
print(a*b)
print(a/b)

[-3 -3  3]
[ 4 10  0]
[0.25 0.4   inf]


/tmp/ipykernel_12328/1458566671.py:4: RuntimeWarning: divide by zero encountered in divide
  print(a/b)


# Repeat and tile

In [70]:
#Repeat each element in array
np.repeat(b, 3)

array([4, 4, 4, 5, 5, 5, 0, 0, 0])

In [71]:
#Repeat all the array
np.tile(b, 3)

array([4, 5, 0, 4, 5, 0, 4, 5, 0])

In [72]:
c = np.arange(9)
c = c.reshape(3, 3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.tile(c, 3)

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8]])

# Expotenial Function

In [74]:
c**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [75]:
a / (c ** 2)

/tmp/ipykernel_12328/1288180403.py:1: RuntimeWarning: divide by zero encountered in divide
  a / (c ** 2)


array([[       inf, 2.        , 0.75      ],
       [0.11111111, 0.125     , 0.12      ],
       [0.02777778, 0.04081633, 0.046875  ]])

# Comparison


In [76]:
c > 3

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

# Universal Function

In [78]:
x = np.array([0, 1, 2, 3])
x**3

array([ 0,  1,  8, 27])

In [79]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [80]:
np.sin(x)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [81]:
np.cos(x)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [82]:
np.round(np.sin(x))

array([0., 1., 1., 0.])

In [83]:
np.floor(np.sin(x))

array([0., 0., 0., 0.])

In [84]:
np.ceil(np.cos(x))

array([ 1.,  1., -0., -0.])

In [85]:
np.fix(np.tan(x))

array([ 0.,  1., -2., -0.])

In [86]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [88]:
np.log(x)

/tmp/ipykernel_12328/1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [89]:
np.unique(x)

array([0, 1, 2, 3])

In [91]:
np.mean(x)

np.float64(1.5)

In [92]:
np.var(x)

np.float64(1.25)

In [93]:
np.std(a)

np.float64(0.816496580927726)

In [94]:
np.cumsum(x)

array([0, 1, 3, 6])

In [95]:
np.max(a)

np.int64(3)

In [96]:
np.min(x)

np.int64(0)

In [97]:
np.argmax(x)

np.int64(3)

In [98]:
np.argmin(a)

np.int64(0)

In [100]:
x.sum()

np.int64(6)

In [101]:
x.mean()

np.float64(1.5)

In [102]:
x.var()

np.float64(1.25)

In [103]:
x.std()

np.float64(1.118033988749895)

In [104]:
x.cumsum()

array([0, 1, 3, 6])

In [105]:
x.mean(axis = 0)

np.float64(1.5)

In [108]:
x = x.reshape(2, 2)
x.mean(axis=1)

array([0.5, 2.5])

In [109]:
np.random.seed(123)

# Random number

In [110]:
np.random.randint(10)

2

In [111]:
np.random.randint(1,11)

3

In [114]:
while True:
  num = np.random.randint(1, 10000000000)
  print(num)
  if num in np.arange(1, 1000000000):
    break

1610124383
5716761103
4726399841
4529845937
6729778047


KeyboardInterrupt: 

In [115]:
x = np.array([0, 1, 2, 3, 4])
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [116]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [117]:
a = np.random.randint(1, 11, size = 1000)
a

array([ 6,  7,  8,  1,  7,  5,  2,  5,  3,  3,  2,  1, 10,  2,  2,  7,  7,
        4, 10,  7,  8,  8,  7,  2, 10,  4,  8,  3,  4,  9,  1,  4,  4, 10,
        9,  7,  4,  8,  6,  9,  5,  9,  6,  2,  8,  3,  8,  9,  2,  8,  2,
        9,  2, 10,  3,  4,  5,  3,  1,  8,  6, 10,  9,  6,  1,  6,  6,  2,
        4,  9,  1,  9,  1,  1, 10,  3,  6,  2,  3,  4,  1,  7,  8,  4, 10,
        8, 10,  5,  9,  1, 10,  8,  1,  1,  3,  5, 10,  2, 10,  6,  9,  6,
        7,  9,  5,  9,  5,  2,  4,  3,  8,  1,  7,  3,  8,  4,  7,  5,  3,
        7, 10, 10,  5,  8,  1,  4,  4,  2,  3,  2,  4,  1,  5,  8,  5,  5,
        8,  7,  4,  4, 10,  7,  8,  5, 10,  2,  8,  5,  1,  2,  3,  4, 10,
        1,  7,  9,  3,  5,  2, 10,  7,  1,  4,  6,  3, 10,  7,  8, 10,  6,
        8,  6,  5,  5,  8,  9,  1,  3,  3,  1,  8,  2,  2,  1,  3,  8,  6,
       10,  4,  4,  7,  6,  5,  9, 10,  7,  5,  9,  1,  7,  5, 10,  1,  1,
        6,  9,  1,  9,  2,  7,  5,  8,  3,  6,  5,  7,  4,  1,  5, 10, 10,
        1,  3,  8,  7,  1

In [118]:
a.size

1000

In [119]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
np.median(a)

np.float64(5.0)

In [121]:
np.sum(a)

np.int64(5462)

In [122]:
np.round(np.var(a), 2)

np.float64(8.14)

In [123]:
set(a)

{np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10)}

In [124]:
a = np.array([3,2,4,5,32,5,62,345,2])
a.argmax()

np.int64(7)

In [126]:
a.argmin()

np.int64(1)

# Linear Algebra

In [129]:
a = np.array([0, 1, 2, 3]).reshape(2, 2)
a

array([[0, 1],
       [2, 3]])

In [128]:
b = np.array([3, 4, 2, 3]).reshape(2, 2)
b

array([[3, 4],
       [2, 3]])

In [130]:
a.dot(b)

array([[ 2,  3],
       [12, 17]])

In [131]:
np.dot(a, b)

array([[ 2,  3],
       [12, 17]])

In [132]:
np.transpose(a)

array([[0, 2],
       [1, 3]])

In [133]:
a.transpose()

array([[0, 2],
       [1, 3]])

In [134]:
np.linalg.inv(a)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [135]:
np.linalg.det(a)

np.float64(-2.0)

# Index and Slicing

In [136]:
a = np.array([0, 1, 2, 3])
b =  np.array([[0, 1, 2, 3],
               [4, 5, 6, 7],
               [8, 9 , 10, 11]])
a[0]

np.int64(0)

In [138]:
b[0][0]

np.int64(0)

In [139]:
b[0, 2]

np.int64(2)

In [140]:
a1 = np.array([0, 10, 20, 30 ,40 , 50])
a1[5]

np.int64(50)

In [141]:
a1[5] = 80
a1

array([ 0, 10, 20, 30, 40, 80])

In [142]:
a1[[1, 4, 5]]

array([10, 40, 80])

In [143]:
a2 = np.arange(10, 100, 10).reshape(3, 3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [144]:
a2[0, 2]

np.int64(30)

In [145]:
a2[2, 1] = 75

In [146]:
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 75, 90]])

In [147]:
a2[1]

array([40, 50, 60])

In [148]:
a2[1] = np.array([45, 55, 65])

In [149]:
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 75, 90]])

In [150]:
a2[[0, 2],
   [0, 1]]

array([10, 75])

In [151]:
a = np.array([1, 2, 3, 4, 5, 6])
a[a>3]

array([4, 5, 6])

In [152]:
a[a%2 == 0]

array([2, 4, 6])

In [153]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:5]

array([10, 20, 30, 40])

In [154]:
b1[:3]

array([ 0, 10, 20])

In [155]:
b1[2:]

array([20, 30, 40, 50])

In [156]:
a2d = np.arange(1, 10).reshape(3, 3)

In [157]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
a2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [164]:
a2d[:1, 1:]

array([[2, 3]])

In [161]:
a2d[1, 1:]

array([5, 6])

In [166]:
names = np.array(['a', 'b', 'c'])
names=='a'
names[names=='a']

array(['a'], dtype='<U1')

In [178]:
a = np.empty((9, 4))
# for i in range(9):
#   a[i] = i
a

array([[3.21638386e-315, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [2.12199579e-310, 1.16097020e-028, 1.26121729e-076,
        2.67489372e-028],
       [7.25560739e-043, 1.04917183e-153, 5.23081515e-143,
        5.04247188e+174],
       [6.12864780e-062, 2.80065571e-032, 9.30051448e+165,
        4.41280379e-143],
       [3.59751658e+252, 1.46901661e+179, 8.37404147e+242,
        4.31999013e-096],
       [4.82337723e+228, 1.08585450e-042, 1.02875441e-071,
        5.58408915e-091],
       [5.24837473e+170, 1.81623213e-052, 5.04621343e+180,
        1.94918963e-153],
       [5.79564081e+170, 2.34053584e-057, 8.00378317e+169,
        1.00132042e+165],
       [1.04915250e-153, 9.08366791e+223, 5.82381891e-144,
        6.17582057e-322]])

In [179]:
a[[4, 3, 0, 6]]

array([[3.59751658e+252, 1.46901661e+179, 8.37404147e+242,
        4.31999013e-096],
       [6.12864780e-062, 2.80065571e-032, 9.30051448e+165,
        4.41280379e-143],
       [3.21638386e-315, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [5.24837473e+170, 1.81623213e-052, 5.04621343e+180,
        1.94918963e-153]])

In [180]:
a[[-3, -5]]

array([[5.24837473e+170, 1.81623213e-052, 5.04621343e+180,
        1.94918963e-153],
       [3.59751658e+252, 1.46901661e+179, 8.37404147e+242,
        4.31999013e-096]])

In [181]:
a2 = np.arange(20)
mask = (a%5 == 0)
a[mask]


array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 8.37404147e+242,
       5.79564081e+170, 8.00378317e+169])

# Convert array and swap axis

In [183]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [184]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [185]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [186]:
np.dot(arr, arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [187]:
a = np.arange(12).reshape(3, 4)

In [188]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [189]:
a.reshape((4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [190]:
a.transpose((0,1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [191]:
a.transpose(1,0)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [192]:
b = np.arange(16).reshape(2, 2, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [193]:
b.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [194]:
b.transpose(0, 1, 2)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [195]:
b.transpose(2, 1, 0)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [196]:
b.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [197]:
b.swapaxes(0, 1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])